/**
 * @file Version.h
 * @brief Version information for MCP45HVX1.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef MCP45HVX1_VERSION_STRING
#define MCP45HVX1_VERSION_STRING "1.0.0"
#endif

#ifndef MCP45HVX1_BUILD_DATE
#define MCP45HVX1_BUILD_DATE __DATE__
#endif

#ifndef MCP45HVX1_BUILD_TIME
#define MCP45HVX1_BUILD_TIME __TIME__
#endif

#ifndef MCP45HVX1_BUILD_TIMESTAMP
#define MCP45HVX1_BUILD_TIMESTAMP MCP45HVX1_BUILD_DATE " " MCP45HVX1_BUILD_TIME
#endif

#ifndef MCP45HVX1_GIT_COMMIT
#define MCP45HVX1_GIT_COMMIT "unknown"
#endif

#ifndef MCP45HVX1_GIT_STATUS
#define MCP45HVX1_GIT_STATUS "unknown"
#endif

#ifndef MCP45HVX1_VERSION_FULL
#define MCP45HVX1_VERSION_FULL MCP45HVX1_VERSION_STRING " (" MCP45HVX1_GIT_COMMIT ", " MCP45HVX1_BUILD_TIMESTAMP ", " MCP45HVX1_GIT_STATUS ")"
#endif

namespace MCP45HVX1 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = MCP45HVX1_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = MCP45HVX1_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = MCP45HVX1_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = MCP45HVX1_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = MCP45HVX1_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = MCP45HVX1_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = MCP45HVX1_VERSION_FULL;

}  // namespace MCP45HVX1
